### ISSUE TITLE
Race condition with relation data

### ISSUE THREAD

**Issue by yanksyoon** [canonical/kratos-external-idp-integrator#149]
### Bug Description

The unit gets stuck on on Waiting status with the following message:
```
Waiting for Kratos to register provider
```

The relation data exists as can be seen from the following:
```
- relation-id: 27
    endpoint: kratos-external-idp
    related-endpoint: kratos-external-idp
    application-data:
      providers: '[{"client_id": "client_id", "provider": "generic", "secret_backend":
        "relation", "scope": "profile email", "provider_id": "Dex", "client_secret":
        "client_secret", "issuer_url": "http://10.15.119.2:5556/"}]'
    related-units:
      kratos-external-idp-integrator/0:
        in-scope: true
        data:
          egress-subnets: 10.152.183.95/32
          ingress-address: 10.152.183.95
          private-address: 10.152.183.95
```

The workaround has been implemented like so to mitigate the issue: https://github.com/canonical/jenkins-k8s-operator/blob/fc9e56ac5b62c49528c1285160b16d60c3d2c35f/tests/integration/conftest.py#L889-L904

### To Reproduce

Deploy the bundle using the following yaml.
```yaml
---
bundle: kubernetes
name: identity-platform
website: https://github.com/canonical/iam-bundle
issues: https://github.com/canonical/iam-bundle/issues
applications:
  hydra:
    charm: hydra
    revision: 285
    channel: 0.2/stable
    scale: 1
    series: jammy
    trust: true
  kratos:
    charm: kratos
    revision: 495
    channel: 0.4/edge
    scale: 1
    series: jammy
    trust: true
  kratos-external-idp-integrator:
    charm: kratos-external-idp-integrator
    channel: latest/edge
    scale: 1
    series: jammy
  identity-platform-login-ui-operator:
    charm: identity-platform-login-ui-operator
    revision: 135
    channel: 0.3/edge
    scale: 1
    series: jammy
    trust: true
    resources:
      oci-image: 79
  postgresql:
    charm: postgresql-k8s 
    revision: 444
    channel: 14/stable
    series: jammy
    scale: 1
    trust: true
  self-signed-certificates:
    charm: self-signed-certificates
    revision: 52
    channel: latest/edge
    scale: 1
  traefik-admin:
    charm: traefik-k8s
    channel: latest/stable
    series: focal
    scale: 1
    revision: 170
    trust: true
  traefik-public:
    charm: traefik-k8s
    channel: latest/stable
    series: focal
    scale: 1
    revision: 176
    trust: true
relations:
  - [hydra:pg-database, postgresql-k8s:database]
  - [kratos:pg-database, postgresql-k8s:database]
  - [kratos:hydra-endpoint-info, hydra:hydra-endpoint-info]
  - [kratos-external-idp-integrator:kratos-external-idp, kratos:kratos-external-idp]
  - [hydra:admin-ingress, traefik-admin:ingress]
  - [hydra:public-ingress, traefik-public:ingress]
  - [kratos:admin-ingress, traefik-admin:ingress]
  - [kratos:public-ingress, traefik-public:ingress]
  - [identity-platform-login-ui-operator:ingress, traefik-public:ingress]
  - [identity-platform-login-ui-operator:hydra-endpoint-info, hydra:hydra-endpoint-info]
  - [identity-platform-login-ui-operator:ui-endpoint-info, hydra:ui-endpoint-info]
  - [identity-platform-login-ui-operator:ui-endpoint-info, kratos:ui-endpoint-info]
  - [identity-platform-login-ui-operator:kratos-endpoint-info, kratos:kratos-endpoint-info]
  - [traefik-admin:certificates, self-signed-certificates:certificates]
  - [traefik-public:certificates, self-signed-certificates:certificates]
```

juju deploy ./replication.yaml

### Environment

The charm revisions with channels are defined on the yaml above. All the latest (0.4/edge, 0.3/edge has also been tested and the bug can be reproduced).

### Relevant log output

```shell
- relation-id: 27
    endpoint: kratos-external-idp
    related-endpoint: kratos-external-idp
    application-data:
      providers: '[{"client_id": "client_id", "provider": "generic", "secret_backend":
        "relation", "scope": "profile email", "provider_id": "Dex", "client_secret":
        "client_secret", "issuer_url": "http://10.15.119.2:5556/"}]'
    related-units:
      kratos-external-idp-integrator/0:
        in-scope: true
        data:
          egress-subnets: 10.152.183.95/32
          ingress-address: 10.152.183.95
          private-address: 10.152.183.95
```
```


### Additional context

Writing a holistic charm might help with the race conditions! :D
